export const mockData = {
  spotify_connected_account: {
    followers: 12432,
    top_track: "Solar Drift",
    avg_popularity: 72,
    recent_release: "Reflections EP",
    top_genre: "Alt R&B",
    top_tracks: [
      {
        title: "Solar Drift",
        album: "Reflections",
        duration: "3:42",
        popularity: 88,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example",
      },
      {
        title: "Moon Dive",
        album: "Reflections",
        duration: "4:05",
        popularity: 82,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example2",
      },
      {
        title: "Starlight",
        album: "Reflections",
        duration: "3:28",
        popularity: 78,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example3",
      },
      {
        title: "Midnight Flow",
        album: "Reflections",
        duration: "4:12",
        popularity: 75,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example4",
      },
      {
        title: "Crystal Dreams",
        album: "Reflections",
        duration: "3:55",
        popularity: 73,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example5",
      },
      {
        title: "Ocean Waves",
        album: "Reflections",
        duration: "4:22",
        popularity: 71,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example6",
      },
      {
        title: "City Lights",
        album: "Reflections",
        duration: "3:38",
        popularity: 69,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example7",
      },
      {
        title: "Neon Nights",
        album: "Reflections",
        duration: "4:01",
        popularity: 67,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example8",
      },
      {
        title: "Velvet Sky",
        album: "Reflections",
        duration: "3:44",
        popularity: 65,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example9",
      },
      {
        title: "Electric Soul",
        album: "Reflections",
        duration: "4:18",
        popularity: 63,
        cover: "/placeholder.jpg",
        spotify_url: "https://open.spotify.com/track/example10",
      },
    ],
    top_tracks_chart: [
      { name: "Solar Drift", "popularity": 88 },
      { name: "Moon Dive", "popularity": 82 },
      { name: "Electric Soul", "popularity": 78 },
      { name: "Neon Nights", "popularity": 75 },
      { name: "Ocean Waves", "popularity": 71 },
      { name: "Midnight Flow", "popularity": 68 },
      { name: "Crystal Dreams", "popularity": 65 },
      { name: "Urban Pulse", "popularity": 62 },
      { name: "Velvet Touch", "popularity": 58 },
      { name: "Sunset Glow", "popularity": 55 }
    ],
    audio_features: {
      "Solar Drift": {
        tempo: 98,
        energy: 0.8,
        valence: 0.6,
        acousticness: 0.2,
        instrumentalness: 0.0,
        danceability: 0.9,
      },
      "Moon Dive": {
        tempo: 120,
        energy: 0.7,
        valence: 0.5,
        acousticness: 0.1,
        instrumentalness: 0.05,
        danceability: 0.85,
      },
    },
  },
  youtube_connected_account: {
    subscribers: 5320,
    total_views: 195420,
    total_videos: 32,
    most_viewed_video: "Nova Live in Berlin",
    avg_views_per_video: 6106,
    top_videos: [
      {
        title: "Nova Live in Berlin",
        views: 24000,
        likes: 1200,
        comments: 145,
        duration: "12:45",
        published: "2024-09-12",
        thumbnail: "/placeholder.jpg",
        link: "https://youtube.com/watch?v=example1",
      },
      {
        title: "Solar Drift - Official Music Video",
        views: 18500,
        likes: 890,
        comments: 120,
        duration: "3:42",
        published: "2024-10-15",
        thumbnail: "/placeholder.jpg",
        link: "https://youtube.com/watch?v=example2",
      },
      {
        title: "Behind the Scenes - Studio Session",
        views: 15200,
        likes: 675,
        comments: 85,
        duration: "8:32",
        published: "2024-11-01",
        thumbnail: "/placeholder.jpg",
        link: "https://youtube.com/watch?v=example3",
      },
      {
        title: "Moon Dive - Acoustic Version",
        views: 12800,
        likes: 542,
        comments: 67,
        duration: "4:05",
        published: "2024-11-20",
        thumbnail: "/placeholder.jpg",
        link: "https://youtube.com/watch?v=example4",
      },
      {
        title: "Live from the Rooftop",
        views: 9500,
        likes: 423,
        comments: 52,
        duration: "15:20",
        published: "2024-08-22",
        thumbnail: "/placeholder.jpg",
        link: "https://youtube.com/watch?v=example5",
      },
    ],
    top_videos_chart: [
      { name: "Nova Live in Berlin", views: 24000 },
      { name: "Solar Drift - Official MV", views: 18500 },
      { name: "Behind the Scenes", views: 15200 },
      { name: "Moon Dive - Acoustic", views: 12800 },
      { name: "Live from the Rooftop", views: 9500 },
    ],
  },
  instagram_connected_account: {
    followers: 8421,
    posts_last_30_days: 12,
    avg_likes: 346,
    avg_comments: 28,
    most_engaged_post: {
      caption: "Studio vibes...",
      likes: 620,
      comments: 50,
      thumbnail: "/placeholder.jpg",
      link: "https://instagram.com/p/example1",
    },
    engagement_over_time: [
      { date: "2024-11-01", engagement: 380 },
      { date: "2024-11-02", engagement: 420 },
      { date: "2024-11-03", engagement: 390 },
      { date: "2024-11-04", engagement: 450 },
      { date: "2024-11-05", engagement: 510 },
      { date: "2024-11-06", engagement: 480 },
      { date: "2024-11-07", engagement: 520 },
    ],
    top_posts_chart: [
      { caption: "Studio vibes...", engagement: 670 },
      { caption: "New track dropping soon", engagement: 565 },
      { caption: "Tour diary: LA", engagement: 441 },
      { caption: "Behind the scenes magic", engagement: 365 },
      { caption: "Live performance energy", engagement: 485 },
    ],
    top_posts: [
      {
        caption: "Tour diary: LA",
        likes: 410,
        comments: 31,
        thumbnail: "/placeholder.jpg",
        posted: "2024-12-01",
        link: "https://instagram.com/p/example1",
      },
      {
        caption: "New track dropping soon 🎵",
        likes: 520,
        comments: 45,
        thumbnail: "/placeholder.jpg",
        posted: "2024-11-28",
        link: "https://instagram.com/p/example2",
      },
      {
        caption: "Studio session vibes",
        likes: 380,
        comments: 22,
        thumbnail: "/placeholder.jpg",
        posted: "2024-11-25",
        link: "https://instagram.com/p/example3",
      },
      {
        caption: "Grateful for the journey",
        likes: 290,
        comments: 18,
        thumbnail: "/placeholder.jpg",
        posted: "2024-11-20",
        link: "https://instagram.com/p/example4",
      },
      {
        caption: "Behind the scenes magic",
        likes: 340,
        comments: 25,
        thumbnail: "/placeholder.jpg",
        posted: "2024-11-18",
        link: "https://instagram.com/p/example5",
      },
      {
        caption: "Live performance energy",
        likes: 450,
        comments: 35,
        thumbnail: "/placeholder.jpg",
        posted: "2024-11-15",
        link: "https://instagram.com/p/example6",
      },
    ],
  },
  my_alera_releases: {
    dropdown_options: ["(Total)", "Solar Drift", "Echo Pulse"],
    selected_release: "(Total)",
    summary: {
      total_streams: 183920,
      avg_streams_per_release: 22990,
      top_track: "Solar Drift",
      top_platform: "Spotify",
    },
    streams_over_time: [
      { date: "2024-11-01", streams: 5200 },
      { date: "2024-11-02", streams: 7000 },
      { date: "2024-11-03", streams: 6900 },
      { date: "2024-11-04", streams: 8200 },
      { date: "2024-11-05", streams: 7800 },
      { date: "2024-11-06", streams: 9100 },
      { date: "2024-11-07", streams: 8500 },
    ],
    platform_breakdown: [
      { platform: "Spotify", streams: 98000 },
      { platform: "Apple Music", streams: 32000 },
      { platform: "YouTube", streams: 21000 },
      { platform: "Amazon Music", streams: 14000 },
      { platform: "Tidal", streams: 9500 },
      { platform: "Deezer", streams: 5200 },
      { platform: "SoundCloud", streams: 220 },
    ],
    releases: [
      {
        title: "Solar Drift",
        date: "2024-11-01",
        status: "Live",
        cover: "/placeholder.jpg",
        streams: 80000,
        platforms: [
          { platform: "Spotify", streams: 48000 },
          { platform: "Apple Music", streams: 15000 },
          { platform: "YouTube", streams: 10000 },
          { platform: "Amazon Music", streams: 4000 },
          { platform: "Tidal", streams: 1800 },
          { platform: "Deezer", streams: 1200 },
          { platform: "SoundCloud", streams: 0 },
        ],
        daily_streams: [
          { date: "2024-11-01", streams: 2600 },
          { date: "2024-11-02", streams: 3000 },
          { date: "2024-11-03", streams: 3300 },
          { date: "2024-11-04", streams: 3800 },
          { date: "2024-11-05", streams: 3500 },
        ],
      },
      {
        title: "Echo Pulse",
        date: "2024-09-20",
        status: "Live",
        cover: "/placeholder.jpg",
        streams: 42000,
        platforms: [
          { platform: "Spotify", streams: 25000 },
          { platform: "Apple Music", streams: 8000 },
          { platform: "YouTube", streams: 6000 },
          { platform: "Amazon Music", streams: 2000 },
          { platform: "Tidal", streams: 1000 },
          { platform: "Deezer", streams: 0 },
          { platform: "SoundCloud", streams: 0 },
        ],
        daily_streams: [
          { date: "2024-09-20", streams: 1800 },
          { date: "2024-09-21", streams: 2400 },
          { date: "2024-09-22", streams: 2700 },
          { date: "2024-09-23", streams: 2200 },
          { date: "2024-09-24", streams: 2800 },
        ],
      },
    ],
  },
}
